config/routes.rb
GoodsCards::Application.routes.draw do

  root to: 'prices#prepayment'
  get '/welcome' => 'prices#welcome'
  # match '/price_liqui_moly' => 'prices#price_liqui_moly'      # second route

end

app/models/price.rb
class Price < ApplicationRecord
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController

  def prepayment
    pdf = PrepaymentPrice.new
    pdf.print_prepayment
    send_data pdf.render, type: 'application/pdf', filename: 'prepayment.pdf', disposition: 'inline'
  end

end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= form_for(price) do |f| %>
  <% if price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prices</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= link_to 'Show', price %></td>
        <td><%= link_to 'Edit', edit_price_path(price) %></td>
        <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price', new_price_path %>

app/views/prices/new.html.erb
<h1>New Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>

app/views/prices/welcome.html.erb
<ul>
  <h1>Богдашкины прозвища</h1>
  <h3>
    <li>Богдашка-черепашка</li>
    <li>Богдашка-какашка</li>
    <li>Богдашка-чебурашка</li>
    <li>Богдашка-промокашка</li>
  </h3>
</ul>

<p></p>
<ul>
  <h1>Богдашкины достижения</h1>
    <h3>
      <ol>Математика: 5</ol>
      <ol>Русский: 5</ol>
      <ol>Труд: 5</ol>
      <ol>"Русский медведь": 500 место</ol>
  </h3>
</ul>